// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AssetCard: typeof import('./src/components/assetCard.vue')['default']
    BannerCard: typeof import('./src/components/bannerCard.vue')['default']
    CreateLifeInventory: typeof import('./src/components/createLifeInventory.vue')['default']
    CreateMemorialDay: typeof import('./src/components/createMemorialDay.vue')['default']
    DragList: typeof import('./src/components/dragList.vue')['default']
    GridAssetCard: typeof import('./src/components/gridAssetCard.vue')['default']
    NutActionSheet: typeof import('@nutui/nutui-taro')['ActionSheet']
    NutAnimate: typeof import('@nutui/nutui-taro')['Animate']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCellGroup: typeof import('@nutui/nutui-taro')['CellGroup']
    NutCountdown: typeof import('@nutui/nutui-taro')['Countdown']
    NutDatePicker: typeof import('@nutui/nutui-taro')['DatePicker']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutEmpty: typeof import('@nutui/nutui-taro')['Empty']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutNoticebar: typeof import('@nutui/nutui-taro')['Noticebar']
    NutPopover: typeof import('@nutui/nutui-taro')['Popover']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutProgress: typeof import('@nutui/nutui-taro')['Progress']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutRate: typeof import('@nutui/nutui-taro')['Rate']
    NutSwipe: typeof import('@nutui/nutui-taro')['Swipe']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTextarea: typeof import('@nutui/nutui-taro')['Textarea']
    Recorder: typeof import('./src/components/recorder.vue')['default']
    RecordPlay: typeof import('./src/components/recordPlay.vue')['default']
    SelectAlbum: typeof import('./src/components/selectAlbum.vue')['default']
    SvgIcon: typeof import('./src/components/svgIcon.vue')['default']
  }
}
